name: Contrib

on:
  push:
    branches:
      - "main"

env:
  CARGO_TERM_COLOR: always

jobs:
  contrib:
    runs-on: ubuntu-latest
    steps:
      - name: Update Contribute List
        uses: akhilmhdh/contributors-readme-action@v2.3.10
        env:
          GITHUB_TOKEN: ${{ secrets.CONTRIB_JOB }}
